// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyKZctEGXmLnq7Vyw_6Ahw8wkdbu2GVqg',
    appId: '1:200540544963:web:602e1b049f468070ae2776',
    messagingSenderId: '200540544963',
    projectId: 'musify-3fd88',
    authDomain: 'musify-3fd88.firebaseapp.com',
    storageBucket: 'musify-3fd88.firebasestorage.app',
    measurementId: 'G-X7B4NY9G8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UOczsWCutwu7JE5yUVGdH8uhf09N6pc',
    appId: '1:200540544963:android:ab9ca7ffe5595627ae2776',
    messagingSenderId: '200540544963',
    projectId: 'musify-3fd88',
    storageBucket: 'musify-3fd88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRhDXk25XTrYUijohXi3niFIBb_GQGTA',
    appId: '1:200540544963:ios:086874f1948041e4ae2776',
    messagingSenderId: '200540544963',
    projectId: 'musify-3fd88',
    storageBucket: 'musify-3fd88.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfRhDXk25XTrYUijohXi3niFIBb_GQGTA',
    appId: '1:200540544963:ios:086874f1948041e4ae2776',
    messagingSenderId: '200540544963',
    projectId: 'musify-3fd88',
    storageBucket: 'musify-3fd88.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyKZctEGXmLnq7Vyw_6Ahw8wkdbu2GVqg',
    appId: '1:200540544963:web:fdbe901c6423f815ae2776',
    messagingSenderId: '200540544963',
    projectId: 'musify-3fd88',
    authDomain: 'musify-3fd88.firebaseapp.com',
    storageBucket: 'musify-3fd88.firebasestorage.app',
    measurementId: 'G-WSWP2G1X4Y',
  );
}
